title: SQL Stacks
description: My Personal Stack Problems
author: Cherry Catcher
github: https://github.com/cherrycatcher
about: I'm Programmer for Java Web Services. I've interested in SQL languages and Data Management.
google-analytics: UA-156528329-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/cherrycatcher"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://cherrycatcher.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
